services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    networks:
      - internal

networks:
  internal:
    internal: true
