services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - internal
    volumes:
      - emdash_data:/app/data

  redis:
    image: 'redis:alpine'
    networks:
      - internal

volumes:
  emdash_data:

networks:
  internal:
    internal: true
