on:
  schedule:
    - cron: '0 * * * *'

jobs:
  refresh-github-stars:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh GitHub Stars
        run: curl -s https://casperengelmann.com/api/refresh-github-starred
